### ISSUE TITLE
Pertanyaan

### ISSUE THREAD

**Issue by catursawahlunto** [mimamch/wa-multi-session#1]
Maaf saya belum mencoba
 tapi apakah untuk mengirim pesan tombol, gambar, url dan lain lain sama dengan baileys ? atau cuma text saja.

**Comment by mimamch** [comment]
Untuk saat ini hanya tersedia Teks.
Akan tetapi karena library ini berdiri diatas Baileys, maka akan ada fitur-fitur tersebut pada pengembangan selanjutnya
