### ISSUE TITLE
Mas apakah bisa kirim pesan ke grup?

### ISSUE THREAD

**Issue by jenilutfifauzi** [mimamch/wa-multi-session#16]

**Comment by mimamch** [comment]
bisa silahkan gunakan parameter isGroup: true, dan ubah tujuan menjadi id grup

**Comment by jenilutfifauzi** [comment]
cara mengetahui id group gimana mas?

**Comment by FERDIZ-afk** [comment]
> cara mengetahui id group gimana mas?

message.messages[0].key.remoteJid

**Comment by FERDIZ-afk** [comment]
> cara mengetahui id group gimana mas?

whatsapp.onMessageReceived(async (msg) => {
  console.log(msg.key.remoteJid)

});

**Comment by FERDIZ-afk** [comment]
> cara mengetahui id group gimana mas?

Biasanya di akhir nomor atau id nya ada gini

@g.us

**Comment by jenilutfifauzi** [comment]
> > cara mengetahui id group gimana mas?
> 
> Biasanya di akhir nomor atau id nya ada gini
> 
> @g.us

ok om thanks

**Comment by horasjey** [comment]
> whatsapp.onMessageReceived(async (msg) => { console.log(msg.key.remoteJid)
> 
> });

maaf mas, ini di mana letaknya ya mas..?
