### ISSUE TITLE
Cek status pesan yang dikirim

### ISSUE THREAD

**Issue by rahmat-dev** [mimamch/wa-multi-session#2]
Bisa nggak ya kita get messages yang udah dikirim sebelumnya? Saya ada case mau kirim bulk messages terus get messages nya dan cek status nya, apakah berhasil terkirim atau tidak

Terimakasih

**Comment by mimamch** [comment]
Bisa menggunakan logic pada aplikasinya seperti menyimpan setiap pesan yang dikirim lalu status success ketika pesan mengembalikan ID

> Bisa nggak ya kita get messages yang udah dikirim sebelumnya? Saya ada case mau kirim bulk messages terus get messages nya dan cek status nya, apakah berhasil terkirim atau tidak
> 
> Terimakasih
