### ISSUE TITLE
can't connect when using nodemon

### ISSUE THREAD

**Issue by Alwisteins** [mimamch/wa-multi-session#33]
I am trying to apply this library as a WA gateway on my backend server.

I combined the code with my backend server and ran it with 1 command using nodemon.

when I try to run the server and try to make a request on the endpoint to create a session, everything runs normally, the qrcode appears and there are no errors on the server.

but when I try to scan the qrcode, my server always refreshes and causes repeated connections (connecting & connected). so the connection never really connects.

but when I tried to run my server using node command, everything went smoothly and connection to whatsapp was successful

**Comment by mimamch** [comment]
don't use nodemon, because nodemon will watch and restart server if there is changes on file.

**Comment by fpiekarski** [comment]
To
[nodemon.json](https://github.com/mimamch/wa-multi-session/files/15209763/nodemon.json)
 use nodemon, please, create a file nodemon.json in base paath of project like this:
{   
    "ignore": ["lib/*.js", "README","./wa_credentials",".w*"] 
}
