### ISSUE TITLE
Baileys 6.7.4

### ISSUE THREAD

**Issue by mdestafadilah** [mimamch/wa-multi-session#37]
gak di update pak?

**Comment by mimamch** [comment]
Wah ada yang baru ya, belum ada waktu untuk maintenance nih.

**Comment by mdestafadilah** [comment]
> Wah ada yang baru ya, belum ada waktu untuk maintenance nih.

iya pak, effectnya kalo load tinggi pairinginya gagal pak, dan session sebelumny ke hapus

**Comment by mdestafadilah** [comment]
6.7.5  ....
